const MESSAGE_TYPE = {
  NEW_BLOCK: "NEW_BLOCK",
  TRANSACTION: "TRANSACTION",
  REQUEST_CHAIN: "REQUEST_CHAIN",
  RECEIVE_CHAIN: "RECEIVE_CHAIN",
  REQUEST_LATEST: "REQUEST_LATEST",
  REQUEST_PEERS: "REQUEST_PEERS",
};

module.exports = MESSAGE_TYPE;
